### ISSUE TITLE
Disabling the template caching is not working

### ISSUE THREAD

**Issue by brsanthu** [allegro/handlebars-spring-boot-starter#20]
Documentation says that we need to set `handlebars.cache=false` in the `application.properties`, which we have done but it is still being cached. Looked at the code, and it looks like it is hardcoded to [setCache(true)](https://github.com/allegro/handlebars-spring-boot-starter/blob/master/src/main/java/pl/allegro/tech/boot/autoconfigure/handlebars/HandlebarsProperties.java#L36).

Can you please suggest ways to disable cache or make that configurable?

**Comment by platan** [comment]
As you can see in the [documentation,](https://github.com/allegro/handlebars-spring-boot-starter#configuration) Handlebars loads *.hbs files from classpath (`handlebars.prefix: classpath:templates/`) by default. When you edit *.hbs files in `src/main/resources/templates`, Handlebars does not see these changes, because these files are not copied to `build/...` directory (classpath). 
There are 2 simple solutions (I assume you working with Intellij IDEA):
- make project after changes in template file (`Build > Make project` or Ctrl+F9)
- or change configuration for development to by adding `handlebars.prefix: file:src/main/resources/templates/`

Please look [here](https://github.com/spring-projects/spring-boot/issues/34) for more information.

**Comment by brsanthu** [comment]
That was exactly the issue (dreaded Intellij no make on save issue). I setup a macro to save and make on Ctrl+S and is working fine.

With that said, what does this config do? `handlebars.cache=false`

**Comment by sant123** [comment]
I have this configuration working in Netbeans
```
handlebars.suffix=.html
handlebars.cache=false
```
